project_id = "zrtkessqceznopjsljou"

[functions.read-sheets]
verify_jwt = false

[functions.save-to-sheets]
verify_jwt = false

[functions.update-status]
verify_jwt = false

[functions.pencairan-save]
verify_jwt = false

[functions.pencairan-update]
verify_jwt = false
