// Re-export everything from pencairan types for backward compatibility
export {
  type SubmissionStatus,
  type UserRole,
  type DocumentType,
  type Document,
  type Submission,
  type PaymentType,
  type WorkflowStage,
  STATUS_LABELS,
  STATUS_COLORS,
  DOCUMENT_LABELS,
  JENIS_BELANJA_OPTIONS,
  SUB_JENIS_BELANJA,
  getDocumentsByJenisBelanja,
  generateSubmissionId,
  formatDateTime,
  canCreateSubmission,
  canTakeAction,
  canViewDetail,
  canEdit,
  getRelevantTimestamp,
  canReturnFromArsip,
  canReturnFromArsip as canReturnFromKppn,
  getWorkflowStages,
  getStageName,
  isStageCompleted,
  shouldShowSubmission,
  canViewAllSubmissions,
  SUBMITTER_ROLES,
  ROLES_CAN_VIEW_ALL,
} from './pencairan';
