// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrtkessqceznopjsljou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpydGtlc3NxY2V6bm9wanNsam91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2OTE0MDAsImV4cCI6MjA4ODI2NzQwMH0.manA4cQt0AKcfVbmsP00wHuDhIzQLoecDF1F5VWSPHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});